---
- name: AS3 Deploy Application Internal Cert
  hosts: lb
  connection: httpapi
  gather_facts: false

  vars:
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: "443"
    ansible_httpapi_password: "{{ ansible_password }}"
    as3_tenant_name: "CustomerDemo"
    F5_VIP_Name: My-Demo-App-SSL-F5
    F5_VIP_IP: 192.170.12.220
    pool_members:
      - 192.170.10.231
      - 192.170.10.232

  tasks:

    - name: PUSH AS3 Template
      f5networks.f5_bigip.bigip_as3_deploy:
        content: "{{ lookup('template','j2/https.j2', split_lines=False) }}"