---
- name: AS3 Deploy Application Internal Cert
  hosts: f5s
  connection: httpapi
  gather_facts: false

  vars:
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: "443"
    ansible_httpapi_password: "{{ ansible_password }}"

  tasks:

    - name: Setup provider
      ansible.builtin.set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"
          server_port: "443"
          no_f5_teem: yes
          validate_certs: false

    - name: Get Failover State - Module
      f5networks.f5_modules.bigip_command:
        commands: show sys failover
        provider: "{{ provider }}"
      connection: local
      register: f5_info

    - name: PUSH AS3 Template
      f5networks.f5_bigip.bigip_as3_deploy:
        content: "{{ lookup('template','j2/https.j2', split_lines=False) }}"
      when:
      - f5_info.stdout[0].split()[1] |lower == "active"
