---
- name: AS3 Fix Bad SSL
  hosts: f5s
  connection: httpapi
  gather_facts: false

  vars:
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: "443"
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_httpapi_use_proxy: false


  tasks:

    - name: Provision ASM/WAF via Declarative Onboarding
      f5networks.f5_bigip.bigip_do_deploy:
        content: "{{ lookup('template','j2/do_configure_deviceCert.j2', split_lines=False) }}"
      register: task

    - name: Wait for Declarative Onboarding Provision to Complete
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}/mgmt/shared/declarative-onboarding/task/{{ task.task_id }}"
        method: GET
        return_content: true
        status_code: 200
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      register: atc_DO_status
      until: atc_DO_status is success
      retries: 30
      delay: 15
      delegate_to: localhost
      when: task.changed

    - name: Setup provider
      ansible.builtin.set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "443"
          no_f5_teem: yes
          validate_certs: false

    - name: Get Failover State - Module
      f5networks.f5_modules.bigip_command:
        commands: show sys failover
        provider: "{{ provider }}"
      connection: local
      register: f5_info

    - name: CREATE AS3 JSON BODY
      set_fact:
        as3_app_body: "{{ lookup('template', 'j2/as3_template.j2', split_lines=False) }}"
      when:
      - f5_info.stdout[0].split()[1] |lower == "active"
      
    - name: PUSH AS3 Template
      f5networks.f5_bigip.bigip_as3_deploy:
        content: "{{ lookup('template','j2/tenant_base.j2', split_lines=False) }}"
      when:
      - f5_info.stdout[0].split()[1] |lower == "active"